input {
  kafka {
    bootstrap_servers => "kafka:29092"
    topics => ["siem-critical-logs"]
    codec => "json"
    auto_offset_reset => "earliest"
  }
}

filter {
  # Clean up PySpark math vector arrays before indexing to Elasticsearch
  mutate {
    remove_field => ["features", "raw_features", "level_idx", "logger_idx", "cluster_prediction"]
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "anomalygate-alerts-%{+YYYY.MM.dd}"
  }
  
  # Prints out formatted alerts in your terminal console logs
  stdout { codec => rubydebug }
}
